### ISSUE TITLE
По итогам ревью 2024-04-08

### ISSUE THREAD

**Issue by ardashev-dev** [TanaisCompany/rx-template-integrationcbrf#1]
1. Метод WriteToExecLog. Строка лога ошибки и дебага идентичные, лучше обернуть в ресурс. В идеале, я бы рекомендовал рассмотреть вариант кастомного логирования в формате JSON для возможности создания дашборда.
if (result == IntCBRF.PublicConstants.Module.EventResult.Error)
        Logger.ErrorFormat("SystemCode = {0}, EventResult = {1}, EventMessage = {2}", IntCBRF.PublicConstants.Module.SystemCode, result, message);
      else
        Logger.DebugFormat("SystemCode = {0}, EventResult = {1}, EventMessage = {2}", IntCBRF.PublicConstants.Module.SystemCode, result, message);

2. Метод SendNotice.
Рекомендовал бы сделать рассылку уведомлений опциональной возможностью, как правило, таких уведомлений накапливается значительное количество и администраторы не обращают на них внимание, к тому же сильно растет число задач и уведомлений в системе.

3. Лучше бы вынести в настройки ссылки на сервисы ЦБР и заполнять в инициализации значениями по умолчанию.
public const string AddressCBRBanks = "http://cbr.ru/scripts/XML_bic.asp";
public const string AddressCBRCurrencies = "https://www.cbr.ru/scripts/XML_valFull.asp";

4. По стилистике. 
-- Неймспесйы лучше начинать с большой буквы: namespace tanais.IntCBR.Client,
-- Примитивы лучше писать с маленькой буквы: var SendNotice = counter.Error > 0;
-- Наименование переменных лучше делать таким, чтобы было понятно, что находится внутри string xml = GetXMLFromCBR(IntCBRF.Resources.CaseCurrencies); Тут лучше было использовать incomingData/incomingDataXml вместо xml.

**Comment by zlroman** [comment]
Исправления после рецензирования

1. Добавлен справочник с настройками, его инициализация, обложка с функицей вызова настроек. Вынесены парамемтры подключения и логирования.
2. наименование переменных и namespace исправлено
3. WriteToLog - переписали к формату логов

**Comment by ardashev-dev** [comment]
Спасибо!
